version: '3'
services:

    # Web NGINX project
    web: 
        # Image name
        image: nginx:latest

        container_name: 'web_app'

        # Синхронизация файлов "директория на компьютере:директория в контейнере"
        volumes:
            - ./src:/var/www/symfony
            - ./etc/config:/var/configs

        # Проброс портов "внутренний порт на компьютере:внутренний порт в контейнере"
        ports:
            - "80:80"

        # Первая команда, запущенная при запуске контейнера
        command: /bin/sh -c "cp /var/configs/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

        # Перезапускать контейнер всегда, если он упадет (сломается)
        restart: always

    laravel:
        image: php:7.1-fpm
        container_name: 'laravel'
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/symfony

        restart: always

    # mysql:
    #     image: mysql:5.6
    #     container_name: 'web_mysql'
    #     ports:
    #         - "3306:3306"
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root

    #     restart: always

          mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trdb

    
   # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_myadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
